/* This is algorand's implementation of Pointproofs */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#if !defined(GROUP_SWITCHED)
#define POINTPROOFSG1_LEN 48
#endif

#if defined(GROUP_SWITCHED)
#define POINTPROOFSG1_LEN 96
#endif

#if !defined(GROUP_SWITCHED)
#define POINTPROOFSG2_LEN 96
#endif

#if defined(GROUP_SWITCHED)
#define POINTPROOFSG2_LEN 48
#endif

#if !defined(GROUP_SWITCHED)
/**
 * Size for serialized commitment.
 */
#define COMMIT_LEN 49
#endif

#if defined(GROUP_SWITCHED)
/**
 * Size for serialized commitment.
 */
#define COMMIT_LEN 97
#endif

#if !defined(GROUP_SWITCHED)
/**
 * Size for serialized proof.
 */
#define PROOF_LEN 49
#endif

#if defined(GROUP_SWITCHED)
/**
 * Size for serialized proof.
 */
#define PROOF_LEN 97
#endif

/**
 * deserialized prover parameter struct
 */
typedef struct pointproofs_pp {
  void *data;
} pointproofs_pp;

/**
 * serialized prover parameter struct
 */
typedef struct pointproofs_pp_bytes {
  uint8_t *data;
  uintptr_t len;
} pointproofs_pp_bytes;

/**
 * deserialized verifier parameter struct
 */
typedef struct pointproofs_vp {
  void *data;
} pointproofs_vp;

/**
 * serialized verifer parameter struct
 */
typedef struct pointproofs_vp_bytes {
  uint8_t *data;
  uintptr_t len;
} pointproofs_vp_bytes;

/**
 * deserialized commitment struct
 */
typedef struct pointproofs_commitment {
  void *data;
} pointproofs_commitment;

/**
 * serialized commitment struct
 */
typedef struct pointproofs_commitment_bytes {
  uint8_t *data;
  uintptr_t len;
} pointproofs_commitment_bytes;

/**
 * deserialized proof struct
 */
typedef struct pointproofs_proof {
  void *data;
} pointproofs_proof;

/**
 * serialized proof struct
 */
typedef struct pointproofs_proof_bytes {
  uint8_t *data;
  uintptr_t len;
} pointproofs_proof_bytes;

/**
 * non-serialized
 */
typedef struct pointproofs_params {
  struct pointproofs_pp prover;
  struct pointproofs_vp verifier;
} pointproofs_params;

/**
 * values
 */
typedef struct pointproofs_value {
  const uint8_t *data;
  size_t len;
} pointproofs_value;

/**
 * Serializing a prove parameter into bytes
 */
int32_t pointproofs_pp_serial(struct pointproofs_pp pprover, struct pointproofs_pp_bytes *bytes);

void pointproofs_free_pp_string(struct pointproofs_pp_bytes buf);

int32_t pointproofs_pp_deserial(struct pointproofs_pp_bytes pprover, struct pointproofs_pp *prover);

/**
 * Serializing a prove parameter into bytes
 */
int32_t pointproofs_vp_serial(struct pointproofs_vp pverifier, struct pointproofs_vp_bytes *bytes);

void pointproofs_free_vp_string(struct pointproofs_vp_bytes buf);

int32_t pointproofs_vp_deserial(struct pointproofs_vp_bytes pverifier,
                                struct pointproofs_vp *verifier);

/**
 * Serializing commitments into bytes
 */
int32_t pointproofs_commit_serial(struct pointproofs_commitment commit,
                                  struct pointproofs_commitment_bytes *bytes);

void pointproofs_free_commit_string(struct pointproofs_commitment_bytes buf);

/**
 * Deserializeing bytes into commitments
 */
int32_t pointproofs_commit_deserial(struct pointproofs_commitment_bytes commit_bytes,
                                    struct pointproofs_commitment *commit);

/**
 * Serializing proofs into bytes
 */
int32_t pointproofs_proof_serial(struct pointproofs_proof proof,
                                 struct pointproofs_proof_bytes *bytes);

void pointproofs_free_proof_string(struct pointproofs_proof_bytes buf);

/**
 * Deserializeing bytes into proofs
 */
int32_t pointproofs_proof_deserial(struct pointproofs_proof_bytes proof_bytes,
                                   struct pointproofs_proof *proof);

/**
 * Generating a pair of parameters
 */
int32_t pointproofs_paramgen(const uint8_t *seedbuf,
                             size_t seedlen,
                             uint8_t ciphersuite,
                             size_t n,
                             struct pointproofs_params *param);

/**
 * Free prover parameter
 */
void pointproofs_free_prover_params(struct pointproofs_pp pp);

/**
 * Free verifier parameter
 */
void pointproofs_free_verifier_params(struct pointproofs_vp vp);

/**
 * Free commitment
 */
void pointproofs_free_commit(struct pointproofs_commitment commit);

/**
 * Free proof
 */
void pointproofs_free_proof(struct pointproofs_proof proof);

/**
 * Generate a commitment
 */
int32_t pointproofs_commit(struct pointproofs_pp prover,
                           const struct pointproofs_value *values,
                           uintptr_t n,
                           struct pointproofs_commitment *commit);

/**
 * Generate a proof
 */
int32_t pointproofs_prove(struct pointproofs_pp prover,
                          const struct pointproofs_value *values,
                          uintptr_t n,
                          size_t idx,
                          struct pointproofs_proof *proof);

/**
 * Generate a batch proof
 */
int32_t pointproofs_prove_batch_aggregated(struct pointproofs_pp prover,
                                           struct pointproofs_commitment commit,
                                           const struct pointproofs_value *values,
                                           size_t n,
                                           const size_t *idx,
                                           size_t nindexes,
                                           struct pointproofs_proof *proof);

/**
 * update an existing proof
 */
int32_t pointproofs_proof_update(struct pointproofs_pp prover,
                                 struct pointproofs_proof proof,
                                 size_t idx,
                                 size_t changed_idx,
                                 struct pointproofs_value val_old,
                                 struct pointproofs_value val_new,
                                 struct pointproofs_proof *new_proof);

/**
 * update an existing commitment
 */
int32_t pointproofs_commit_update(struct pointproofs_pp prover,
                                  struct pointproofs_commitment com,
                                  size_t changed_idx,
                                  struct pointproofs_value val_old,
                                  struct pointproofs_value val_new,
                                  struct pointproofs_commitment *new_com);

/**
 * verify the proof against the value and commitment
 */
bool pointproofs_verify(struct pointproofs_vp verifier,
                        struct pointproofs_commitment com,
                        struct pointproofs_proof proof,
                        struct pointproofs_value value,
                        size_t idx);

/**
 * aggregate proofs within a same commitment
 */
int32_t pointproofs_same_commit_aggregate(struct pointproofs_commitment com,
                                          const struct pointproofs_proof *proofs,
                                          const size_t *set,
                                          const struct pointproofs_value *values,
                                          size_t nvalues,
                                          size_t param_n,
                                          struct pointproofs_proof *agg_proof);

/**
 * verify an aggregated proof within a same commitment
 */
bool pointproofs_same_commit_batch_verify(struct pointproofs_vp verifier,
                                          struct pointproofs_commitment com,
                                          struct pointproofs_proof proof,
                                          const size_t *set,
                                          const struct pointproofs_value *values,
                                          size_t nvalues);

/**
 * aggregated proofs cross commitments
 */
int32_t pointproofs_x_commit_aggregate_full(const struct pointproofs_commitment *com,
                                            const struct pointproofs_proof *proof,
                                            const size_t *set,
                                            const struct pointproofs_value *values,
                                            const size_t *commit_indices,
                                            size_t no_commits,
                                            size_t param_n,
                                            struct pointproofs_proof *x_proof);

/**
 * aggregated proofs cross commitments
 */
int32_t pointproofs_x_commit_aggregate_partial(const struct pointproofs_commitment *com,
                                               const struct pointproofs_proof *agg_proof,
                                               const size_t *set,
                                               const struct pointproofs_value *values,
                                               const size_t *commit_indices,
                                               size_t no_commits,
                                               size_t param_n,
                                               struct pointproofs_proof *x_proof);

/**
 * verify an aggregated proof across commitments
 */
bool pointproofs_x_commit_batch_verify(struct pointproofs_vp verifier,
                                       const struct pointproofs_commitment *com,
                                       struct pointproofs_proof proof,
                                       const size_t *set,
                                       const struct pointproofs_value *values,
                                       const size_t *commit_indices,
                                       size_t no_commits);
